# Service para expor o PostgreSQL internamente no cluster

apiVersion: v1
kind: Service
metadata:
  name: postgresql  # Nome do service
spec:
  selector:
    app: postgresql  # Seleciona pods com
  ports:
    - port: 5432  # Porta exposta pelo service
      targetPort: 5432  # Porta do container
