apiVersion: v1
kind: ConfigMap
metadata:
  name: app-variaveis-ambiente-kube-news-postgres
data:
  DB_DATABASE: "kube_news"
  DB_USERNAME: "kubeuser"
  DB_PASSWORD: "kubepassword"
  DB_HOST: "postgresql"  # Nome do serviço do PostgreSQL
