apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubenews
spec:
  replicas: 10
  selector:
    matchLabels:
      app: kubenews
  template:
    metadata:
      labels:
        app: kubenews
    spec:
      initContainers:
        - name: wait-for-postgres
          image: postgres:15
          command: ["sh", "-c", "until pg_isready -h $DB_HOST -p 5432; do echo esperando o banco...; sleep 2; done"]
          envFrom:
            - configMapRef:
                name: env-kubedev-news-app    
      containers:
      - name: kubenews
        image: oalexandrino/k8s-kube-news:v1
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: env-kubedev-news-app
        env:
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: secret-kubedev-news-app-and-postgre
                key: DB_PASSWORD
