kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30000
        hostPort: 30000
        protocol: TCP
    extraMounts:
      - hostPath: D:/DEV/kubernetes/PVC/postgre
        containerPath: /mnt/postgres-data
  - role: control-plane
  - role: worker
  - role: worker